/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_houbin_jni_Hello */

#ifndef _Included_com_houbin_jni_Hello
#define _Included_com_houbin_jni_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_houbin_jni_Hello
 * Method:    native_say_hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_houbin_jni_Hello_native_1say_1hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
